### ISSUE TITLE
Create setup matching buttons when form is revised

### ISSUE THREAD

**Issue by racheljsmart** [openreview/openreview-py#1545] opened 2023-02-03 20:29 UTC
PCs sometimes change their minds and decide they want automatic paper matching instead of manual after the venue has been deployed. It would be helpful if they could revise the form and enable the setup matching buttons, currently we have to do this manually.

**Comment by celestemartinez** [comment] 2023-02-09 20:52
I believe we are now always creating the `Paper_Matching_Setup` invitation, precisely because PCs were always changing their mind: https://github.com/openreview/openreview-py/blob/7b503e7f0f3bad5b91919bc7cb2f0182b6835cf9/openreview/venue_request/process/deployProcess.py#L381

I think the issue is that we set the activation date as the submission deadline, so PCs won't be able to see this invitation until the deadline has passed (so they don't try to run the paper matching before the deadline has passed)

Let me know if this fixes this issue or if I am missing something! @racheljsmart @melisabok

**Comment by melisabok** [comment] 2023-02-09 20:59
So then the request from is revised and automatic matching is selected. Does the expertise selection invitation is created and the PC console reviewer reassignment is disabled?

If this is true then we can close this issue.

**Comment by melisabok** [comment] 2023-07-28 15:30
I think this issue is fixed, right?

**Comment by racheljsmart** [comment] 2023-07-28 20:08
I think the issue is fixed

**Closed** 2023-07-28 20:18 UTC
