### ISSUE TITLE
PC Console: export data to a csv/json file?

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#521] opened 2019-12-06 17:45 UTC
The PC Console has very powerful stats, should we add a button to export the data to a json or csv file?
Sometimes PCs want to work with this stats and do something different. 

Thoughts? @zbialecki @carlosmondra @mohituniyal

**Comment by zbialecki** [comment] 2019-12-06 17:47
I think this is a duplicate of #296

**Comment by mohituniyal** [comment] 2020-01-17 14:59
Thanks @zbialecki . Closing this issue as it a duplicate.

**Closed by mohituniyal** 2020-01-17 14:59 UTC
